# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      - run: composer install -n --prefer-dist
      - run: wget https://github.com/infection/infection/releases/download/0.8.1/infection.phar
      - run: wget https://github.com/infection/infection/releases/download/0.8.1/infection.phar.pubkey
      - run: chmod +x infection.phar
      - run: mkdir -p build/logs
      - run: ./vendor/bin/phpunit -c phpunit.xml --testdox
      - run: ./vendor/bin/phpstan analyse -c phpstan.neon
      - run: ./infection.phar --min-msi=90 --min-covered-msi=100
      - run: touch build/logs/infection-log.txt
      - run: cat build/logs/infection-log.txt
      - run: ./vendor/bin/php-coveralls